name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync files to server (exclude env + venv)
        run: |
          rsync -av --delete \
            --exclude '.env' \
            --exclude 'venv/' \
            /home/ubuntu/actions-runner/_work/PortfolioFlaskApp/PortfolioFlaskApp/ \
            /home/ubuntu/PortfolioFlaskApp/

      - name: Install dependencies
        run: |
          cd /home/ubuntu/PortfolioFlaskApp
          python3 -m venv venv || true
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restart Gunicorn
        run: |
          sudo systemctl restart flaskapp
